apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksstasdemo-4bca"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksstasdemo-4bca"
  template:
    metadata:
      labels:
        app: "aksstasdemo-4bca"
    spec:
      containers:
        - name: "aksstasdemo-4bca"
          image: "acrstasdemo.azurecr.io/aksstasdemo"
          ports:
          - containerPort: 80