apiVersion: v1
kind: Service
metadata:
    name: "aksstasdemo-4bca"
    labels:
        app: "aksstasdemo-4bca"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksstasdemo-4bca"